apiVersion: v1
kind: Template
labels:
  template: ignite-vertex-sample
message: |-
  The following service(s) have been created in your project: ${APP_NAME}, ${OPENSHIFT_SERVICE_IGNITE}

  For more information about using this template, including OpenShift considerations, see
  https://github.com/dsevost/vertx-ignite-kubernetes/blob/master/README.md.
metadata:
  annotations:
    description: An example Apache Ignite and Eclipse Vert.x. For more information about using this template,
      including OpenShift considerations, see https://github.com/dsevost/vertx-ignite-kubernetes/blob/master/README.md.
    openshift.io/display-name: Apache Ignite and Eclipse Vert.x
    openshift.io/documentation-url: https://github.com/dsevost/vertx-ignite-kubernetes
    openshift.io/long-description: This template defines resources needed to develop
      a Timestamp application, including a build configuration, application deployment
      configuration, and security objects for Grid Nodes discovering.
    iconClass: icon-openjdk
    tags: quickstart,java,vertx,ignite
  description: Apacge Ignite and Exclipse Vert.x demo
  name: ignite-vertex-sample
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URI}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:latest
          namespace: openshift
#        incremental: ${INCREMENTAL_BUILD}
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_HOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${WEB_HOOK_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
      build: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentConfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          env:
          - name: OPENSHIFT_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: OPENSHIFT_SERVICE_IGNITE
            value: ${OPENSHIFT_SERVICE_IGNITE}
          - name: JAVA_APP_JAR
            value: app-fat.jar
          image: ' '
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
        serviceAccount: ${IGNITE_SERVICE_ACCOUNT}
        serviceAccountName: ${IGNITE_SERVICE_ACCOUNT}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${OPENSHIFT_SERVICE_IGNITE}
  spec:
    ports:
    - port: 9042
      protocol: TCP
      targetPort: 9042
    selector:
      app: ${APP_NAME}
      deploymentConfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
    clusterIP: 'None'
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ${APP_NAME}
      deploymentConfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${IGNITE_SERVICE_ACCOUNT}
- apiVersion: v1
  kind: Role
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${IGNITE_DISCOVERER_ROLE}
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
#
# This rolebinding definition requires OpenShift 3.7+
#
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app: ${APP_NAME}
    name: ignite
  roleRef:
    kind: Role
    name: ${IGNITE_DISCOVERER_ROLE}
  subjects:
  - kind: ServiceAccount
    name: ${IGNITE_SERVICE_ACCOUNT}
##
## This rolebinding definition requires ${CURRENT_PROJECT_NAME} parameter to be defined
##
#- apiVersion: v1
#  kind: RoleBinding
#  metadata:
#    labels:
#      app: ${APP_NAME}
#    name: ignite
#    namespace: ${CURRENT_PROJECT_NAME}
#  roleRef:
#    kind: Role
#    name: ${IGNITE_DISCOVERER_ROLE}
#  subjects:
#  - kind: ServiceAccount
#    name: ${IGNITE_SERVICE_ACCOUNT}
parameters:
- name: APP_NAME
  description: A built application name. All created objects will have label app=${APP_NAME}
  value: timestamp
- name: SOURCE_REPOSITORY_URI
  description: Source repository URL
  value: https://github.com/dsevost/vertx-ignite-kubernetes
- name: SOURCE_REPOSITORY_REF
  description: Branch or Tag in Source repository
  value: ""
- name: GITHUB_HOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{10}"
- name: WEB_HOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{10}"
- name: MAVEN_MIRROR_URL
  description: Maven reposritory custom URL. If there is one or you do not have an internet connection user this variable to point a local Maven repository
  value: ''
#- name: INCREMENTAL_BUILD
#  description: Set to "True" if you would like an incremental builds
#  value: "False"
- name: OPENSHIFT_SERVICE_IGNITE
  description: A special headless service provides lookup for Ignite nodes in cluster
  value: ignite-discoverer
- name: IGNITE_SERVICE_ACCOUNT
  description: Application with Apache Ignite should have nessessary privileges to retrieve ednpoints from ${OPENSHIFT_SERVICE_IGNITE}. And this is account
    name who will have special role to query endpoints.
  value: ignite-sa
- name: IGNITE_DISCOVERER_ROLE
  description: Application with Apache Ignite should have nessessary privileges to retrieve ednpoints. This role permits running PODs to get list of
    Ignite service discover.
  value: ignite-discoverer
#- name: CURRENT_PROJECT_NAME
#  required: true
